version: '3'

services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network
    depends_on:
      - tampering
      - auth

  gestor_incidentes_principal:
    build:
      context: ./gestor_incidentes
    ports:
      - "5001:5000"
    environment:
      - INSTANCE_TYPE=principal
    networks:
      - app-network

  auth:
    build:
      context: ./auth
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  tampering:
    build:
      context: ./tampering
    ports:
      - "5003:5000"
    networks:
      - app-network
    depends_on:
      - gestor_incidentes_principal


volumes:
  sqlite_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
