apiVersion: 1
groups:
    - orgId: 1
      name: Fallos Gestor Incidente
      folder: Alertas Gestor Incidentes
      interval: 10s
      rules:
        - uid: adx15jr49l3wgc
          title: Discord Web Hook
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus_uid1
              model:
                editorMode: code
                expr: rate(experimento_1_data_total{status_code="500", exported_instance!="API GATEWAY"}[1m]) * 60
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 40
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Discord Web Hook
