apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: 'Alertas Gestor Incidentes'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /var/lib/grafana/dashboards